### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by alfandango** [Quacksilber/BatchRenderObjects#1]
I'm getting the following error when using this.  Any suggestions for what could be going wrong?
![batch images error](https://user-images.githubusercontent.com/70297661/167518005-752213eb-62a3-4de6-bbf2-057b99c91fa9.jpg)

**Comment by Quacksilber** [comment]
Probably some internal changes in the blender python api. The original addon was written for and tested with version 2.8, should be fixed now!
