### ISSUE TITLE
Feature Request - Material Override

### ISSUE THREAD

**Issue by alfandango** [Quacksilber/BatchRenderObjects#2]
Absolutely great addon, it works perfectly after your recent update.  Would it be possible to include a 'material override' drop down to set the material properties of the files being rendered?

**Comment by Quacksilber** [comment]
Thanks, I appreciate it!
I implemented a basic version of what you described, would you mind to test it? 

Just download the python file from [here](https://github.com/Quacksilber/BatchRenderObjects/blob/6757deae3f4e2d439b072985bb0c721cdf728fd6/batch-render-objects.py), and install it, just like any addon.

**Comment by alfandango** [comment]
This is brilliant!  Works great :)
