### ISSUE TITLE
Object rotation issue

### ISSUE THREAD

**Issue by alfandango** [Quacksilber/BatchRenderObjects#4]
Still loving this add-on. I've been using this successfully for a while but recently the imported objects are all rotating.  I've tested this with various versions of the add-on and different Blender releases.  Any ideas what could be happening?

Would it possible to include orientation checkbox to the add-on panel for extra control?

**Comment by Quacksilber** [comment]
Hi!
I'm having trouble replicating your problem. Which Blender version are you using and which filetype? Have you tried to import one of the rotating models, using Blenders internal importer?
How exactly are the models rotating? Is it possible, that a different coordinate system (e.g. y-up) is beeing applied? If so, have you tried changing the "up" and "forward" options in the addons import-dialog?

**Comment by alfandango** [comment]
You're absolutely correct, I didn't realise the add-on had axis options within the import-dialog so I had "up" and "forward" incorrectly set.

Thanks again for the quick response - Amazing add-on!

**Comment by Quacksilber** [comment]
No problem, very much appreciated!
